// scripts/deploy.js
// -----------------------------------------------------------------------------
// Deploys PitchSideBets (+ MockUSDT on non-mainnet) and writes the resulting
// addresses to deployments/<network>.json so the app can pick them up.
//
//   npx hardhat run scripts/deploy.js                     # hardhat in-proc (dry)
//   npx hardhat run scripts/deploy.js --network bscTestnet # real testnet
//
// Env (contracts/.env), only needed for a real network:
//   BSC_TESTNET_RPC, DEPLOYER_PRIVATE_KEY
//   USDT_ADDRESS  - reuse an existing test USDT instead of deploying MockUSDT
//   DAO_ADDRESS   - the 5% DAO fee wallet (defaults to the deployer)
// -----------------------------------------------------------------------------

const fs = require('fs')
const path = require('path')
const hre = require('hardhat')
const { ethers, network } = hre

async function main() {
  const [deployer] = await ethers.getSigners()
  console.log(`Network:  ${network.name}`)
  console.log(`Deployer: ${deployer.address}`)
  const bal = await ethers.provider.getBalance(deployer.address)
  console.log(`Balance:  ${ethers.formatEther(bal)} (native)`)

  // 1) USDT — reuse an existing token if USDT_ADDRESS is set, else deploy a mock.
  let usdtAddress = process.env.USDT_ADDRESS
  if (usdtAddress) {
    console.log(`Using existing USDT at ${usdtAddress}`)
  } else {
    console.log('Deploying MockUSDT…')
    const MockUSDT = await ethers.getContractFactory('MockUSDT')
    const usdt = await MockUSDT.deploy()
    await usdt.waitForDeployment()
    usdtAddress = await usdt.getAddress()
    console.log(`MockUSDT:      ${usdtAddress}`)
  }

  // 2) DAO fee wallet — defaults to the deployer (fine for testnet).
  const daoAddress = process.env.DAO_ADDRESS || deployer.address
  console.log(`DAO wallet:    ${daoAddress}`)

  // 3) The escrow.
  console.log('Deploying PitchSideBets…')
  const Bets = await ethers.getContractFactory('PitchSideBets')
  const bets = await Bets.deploy(usdtAddress, daoAddress)
  await bets.waitForDeployment()
  const betsAddress = await bets.getAddress()
  console.log(`PitchSideBets: ${betsAddress}`)

  // 4) Persist addresses so renderer/wallet.js can load them.
  const chainId = Number((await ethers.provider.getNetwork()).chainId)
  const out = {
    network: network.name,
    chainId,
    usdt: usdtAddress,
    dao: daoAddress,
    bets: betsAddress,
    deployedAt: new Date().toISOString()
  }
  const dir = path.join(__dirname, '..', 'deployments')
  fs.mkdirSync(dir, { recursive: true })
  const file = path.join(dir, `${network.name}.json`)
  fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n')
  console.log(`\nWrote ${path.relative(process.cwd(), file)}`)

  // Also emit the ESM module the renderer imports, so the app talks to this
  // deployment with no manual copy step. (Local hardhat deploys are ephemeral;
  // pass --network bscTestnet for a persistent one.)
  const modPath = path.join(__dirname, '..', '..', 'renderer', 'contract', 'deployment.js')
  const mod =
    `// renderer/contract/deployment.js — AUTO-GENERATED by contracts/scripts/deploy.js\n` +
    `// Deployed to ${out.network} (chainId ${out.chainId}) at ${out.deployedAt}.\n` +
    `export default ${JSON.stringify({ network: out.network, chainId: out.chainId, usdt: out.usdt, dao: out.dao, bets: out.bets }, null, 2)}\n`
  fs.writeFileSync(modPath, mod)
  console.log(`Wrote ${path.relative(process.cwd(), modPath)}`)
  console.log(JSON.stringify(out, null, 2))
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
