// scripts/export-abi.js
// Copy the compiled ABIs the app needs into renderer/contract/ so the renderer
// can import them directly (no artifacts/ dependency at runtime).
const fs = require('fs')
const path = require('path')

const targets = [
  ['PitchSideBets', 'contracts/PitchSideBets.sol'],
  ['MockUSDT', 'contracts/test/MockUSDT.sol']
]

const outDir = path.join(__dirname, '..', '..', 'renderer', 'contract')
fs.mkdirSync(outDir, { recursive: true })

for (const [name, sol] of targets) {
  const artPath = path.join(__dirname, '..', 'artifacts', sol, `${name}.json`)
  const art = JSON.parse(fs.readFileSync(artPath, 'utf8'))
  // Emit an ES module (export default [...]) so the renderer can `import` it in
  // Chromium without JSON import-assertions (which vary by runtime version).
  const body = `// AUTO-GENERATED by contracts/scripts/export-abi.js — do not edit.\nexport default ${JSON.stringify(art.abi, null, 2)}\n`
  fs.writeFileSync(path.join(outDir, `${name}.abi.js`), body)
  console.log(`wrote renderer/contract/${name}.abi.js (${art.abi.length} entries)`)
}
