// AUTO-GENERATED by contracts/scripts/export-abi.js — do not edit.
export default [
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'usdt_',
        type: 'address'
      },
      {
        internalType: 'address',
        name: 'dao_',
        type: 'address'
      }
    ],
    stateMutability: 'nonpayable',
    type: 'constructor'
  },
  {
    inputs: [],
    name: 'AlreadyWithdrawn',
    type: 'error'
  },
  {
    inputs: [],
    name: 'BadOutcomeCount',
    type: 'error'
  },
  {
    inputs: [],
    name: 'BettingClosed',
    type: 'error'
  },
  {
    inputs: [],
    name: 'CannotCancelNow',
    type: 'error'
  },
  {
    inputs: [],
    name: 'CloseInPast',
    type: 'error'
  },
  {
    inputs: [],
    name: 'DisputeWindowActive',
    type: 'error'
  },
  {
    inputs: [],
    name: 'InvalidOutcome',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotHost',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotOpen',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotProposed',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotWinner',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NothingToClaim',
    type: 'error'
  },
  {
    inputs: [],
    name: 'ReentrancyGuardReentrantCall',
    type: 'error'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address'
      }
    ],
    name: 'SafeERC20FailedOperation',
    type: 'error'
  },
  {
    inputs: [],
    name: 'UnknownBet',
    type: 'error'
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error'
  },
  {
    inputs: [],
    name: 'ZeroAmount',
    type: 'error'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'BetCancelled',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'host',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'matchRef',
        type: 'string'
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'question',
        type: 'string'
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'outcomeCount',
        type: 'uint8'
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'closesAt',
        type: 'uint64'
      }
    ],
    name: 'BetCreated',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'bettor',
        type: 'address'
      },
      {
        indexed: true,
        internalType: 'uint8',
        name: 'outcome',
        type: 'uint8'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'BetJoined',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'uint8',
        name: 'winningOutcome',
        type: 'uint8'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'daoCut',
        type: 'uint256'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'hostCut',
        type: 'uint256'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'winnersPool',
        type: 'uint256'
      }
    ],
    name: 'BetResolved',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'uint8',
        name: 'proposedOutcome',
        type: 'uint8'
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'disputeUntil',
        type: 'uint64'
      }
    ],
    name: 'ResultProposed',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'bettor',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'StakeRefunded',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'bettor',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'WinningsClaimed',
    type: 'event'
  },
  {
    inputs: [],
    name: 'BPS_DENOMINATOR',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'DAO_BPS',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'HOST_BPS',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'MIN_DISPUTE_WINDOW',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'betCount',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'cancelBet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'confirmResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'matchRef',
        type: 'string'
      },
      {
        internalType: 'string',
        name: 'question',
        type: 'string'
      },
      {
        internalType: 'uint8',
        name: 'outcomeCount',
        type: 'uint8'
      },
      {
        internalType: 'uint64',
        name: 'closesAt',
        type: 'uint64'
      }
    ],
    name: 'createBet',
    outputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [],
    name: 'dao',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'getBet',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'host',
            type: 'address'
          },
          {
            internalType: 'string',
            name: 'matchRef',
            type: 'string'
          },
          {
            internalType: 'string',
            name: 'question',
            type: 'string'
          },
          {
            internalType: 'uint8',
            name: 'outcomeCount',
            type: 'uint8'
          },
          {
            internalType: 'uint64',
            name: 'closesAt',
            type: 'uint64'
          },
          {
            internalType: 'uint64',
            name: 'disputeUntil',
            type: 'uint64'
          },
          {
            internalType: 'uint8',
            name: 'proposedOutcome',
            type: 'uint8'
          },
          {
            internalType: 'uint8',
            name: 'winningOutcome',
            type: 'uint8'
          },
          {
            internalType: 'enum PitchSideBets.Status',
            name: 'status',
            type: 'uint8'
          },
          {
            internalType: 'uint256',
            name: 'totalPool',
            type: 'uint256'
          }
        ],
        internalType: 'struct PitchSideBets.Bet',
        name: '',
        type: 'tuple'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        internalType: 'uint8',
        name: 'outcome',
        type: 'uint8'
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'joinBet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      },
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8'
      }
    ],
    name: 'outcomePool',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      },
      {
        internalType: 'uint8',
        name: 'proposedOutcome',
        type: 'uint8'
      },
      {
        internalType: 'uint64',
        name: 'disputeWindow',
        type: 'uint64'
      }
    ],
    name: 'proposeResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'betId',
        type: 'uint256'
      }
    ],
    name: 'refund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      },
      {
        internalType: 'address',
        name: '',
        type: 'address'
      },
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8'
      }
    ],
    name: 'stakeOf',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'usdt',
    outputs: [
      {
        internalType: 'contract IERC20',
        name: '',
        type: 'address'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      },
      {
        internalType: 'address',
        name: '',
        type: 'address'
      }
    ],
    name: 'withdrawn',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  }
]
